import type { CommandModule, Argv } from 'yargs';
import chalk from 'chalk';
import inquirer from 'inquirer';
import fs from 'fs';
import path from 'path';
import { generateGitignoreContent, generateReadmeContent } from '@stackcode/core';

export const generateCommand: CommandModule = {
    command: 'generate <filetype>',
    describe: 'Generate common project files.',
    builder: (yargs: Argv) => {
        return yargs
            .command(
                'gitignore',
                'Generates a .gitignore file for Node.js projects.',
                {},
                async () => {
                    const gitignorePath = path.join(process.cwd(), '.gitignore');
                    if (fs.existsSync(gitignorePath)) {
                        console.log(chalk.yellow('A .gitignore file already exists. Operation cancelled to avoid overwriting.'));
                        return;
                    }
                    const content = generateGitignoreContent('node');
                    fs.writeFileSync(gitignorePath, content);
                    console.log(chalk.green.bold('✔ Success! .gitignore file generated.'));
                }
            )
            .command(
                'readme',
                'Generates a rich README.md template file.',
                {},
                async () => {
                    const readmePath = path.join(process.cwd(), 'README.md');
                    if (fs.existsSync(readmePath)) {
                        const { overwrite } = await inquirer.prompt([{
                            type: 'confirm',
                            name: 'overwrite',
                            message: 'A README.md file already exists. Do you want to overwrite it?',
                            default: false,
                        }]);
                        if (!overwrite) {
                            console.log(chalk.yellow('Operation cancelled.'));
                            return;
                        }
                    }
                    const content = generateReadmeContent({
                        projectName: 'New Project',
                        description: 'A project generated by StackCode.',
                        authorName: 'Author'
                    });
                    fs.writeFileSync(readmePath, content);
                    console.log(chalk.green.bold('✔ Success! README.md template generated.'));
                }
            );
    },
    handler: () => {
        console.log(chalk.yellow('Please specify a file type to generate (e.g., gitignore, readme).'));
    }
};