import type { CommandModule } from 'yargs';
import inquirer from 'inquirer';
import chalk from 'chalk';
import fs from 'fs';
import path from 'path';
import {
    scaffoldProject,
    setupHusky,
    generateReadmeContent,
    generateGitignoreContent,
    runCommand,
} from '@stackcode/core';

export const initCommand: CommandModule = {
    command: 'init',
    describe: 'Starts an interactive wizard to set up a new project.',
    builder: {},
    handler: async () => {
        console.log(chalk.cyan.bold("Welcome to StackCode! Let's set up your new project."));
        console.log(chalk.gray('----------------------------------------------------'));

        const answers = await inquirer.prompt([
            {
                type: 'input',
                name: 'projectName',
                message: "What is the name of your project?",
                validate: (input) => input ? true : 'Project name cannot be empty.',
            },
            {
                type: 'input',
                name: 'description',
                message: 'Provide a short description of the project:',
                default: 'A new project generated by StackCode.',
            },
            {
                type: 'input',
                name: 'authorName',
                message: 'What is the author\'s name?',
            },
            {
                type: 'list',
                name: 'stack',
                message: 'Which stack would you like to use?',
                choices: [{ name: 'Node.js + TypeScript', value: 'node-ts' }],
            },
            {
                type: 'checkbox',
                name: 'features',
                message: 'Which additional features do you want to include?',
                choices: [
                    { name: 'Docker support', value: 'docker', checked: true },
                    { name: 'Husky for commit linting', value: 'husky', checked: true },
                ],
            },
        ]);

        const projectPath = path.join(process.cwd(), answers.projectName);

        if (fs.existsSync(projectPath)) {
            const { overwrite } = await inquirer.prompt([{
                type: 'confirm',
                name: 'overwrite',
                message: chalk.yellow(`Directory '${answers.projectName}' already exists. Overwrite?`),
                default: false
            }]);
            if (!overwrite) {
                console.log(chalk.red('Operation cancelled.'));
                return;
            }
        }
        
        console.log(chalk.gray('----------------------------------------------------'));
        console.log(chalk.green('🚀 Starting project setup...'));

        const replacements = {
            projectName: answers.projectName,
            description: answers.description,
            authorName: answers.authorName,
        };

        console.log(chalk.blue('   -> Creating project structure...'));
        scaffoldProject({
            projectPath,
            stack: answers.stack,
            features: answers.features,
            replacements,
        });

        console.log(chalk.blue('   -> Generating README.md...'));
        fs.writeFileSync(path.join(projectPath, 'README.md'), generateReadmeContent(replacements));
        
        console.log(chalk.blue('   -> Generating .gitignore...'));
        fs.writeFileSync(path.join(projectPath, '.gitignore'), generateGitignoreContent('node'));
        
        if (answers.features.includes('husky')) {
            console.log(chalk.blue('   -> Configuring Husky...'));
            setupHusky(projectPath);
        }

        console.log(chalk.blue('   -> Initializing Git repository...'));
        await runCommand('git', ['init'], { cwd: projectPath });
        
        console.log(chalk.blue('   -> Installing dependencies (this may take a moment)...'));
        await runCommand('npm', ['install'], { cwd: projectPath });

        console.log(chalk.gray('----------------------------------------------------'));
        console.log(chalk.green.bold('✅ Success! Your project is ready.'));
        console.log(chalk.cyan('\nNext steps:'));
        console.log(`   1. cd ${answers.projectName}`);
        console.log('   2. Open the project in your favorite editor.');
        console.log('   3. Start coding! 🎉');
    },
};