import type { CommandModule } from 'yargs';
import inquirer from 'inquirer';
import chalk from 'chalk';
import fs from 'fs';
import path from 'path';
import {
    scaffoldProject,
    setupHusky,
    generateReadmeContent,
    generateGitignoreContent,
    runCommand,
} from '@stackcode/core';
import { t } from '@stackcode/i18n';

export const initCommand: CommandModule = {
    command: 'init',
    describe: 'Starts an interactive wizard to set up a new project.',
    builder: {},
    handler: async () => {
        console.log(chalk.cyan.bold(t('init.welcome')));
        console.log(chalk.gray('----------------------------------------------------'));

        const answers = await inquirer.prompt([
            {
                type: 'input',
                name: 'projectName',
                message: t('init.prompt.project_name'),
                validate: (input) => input ? true : t('init.prompt.project_name_error'),
            },
            {
                type: 'input',
                name: 'description',
                message: t('init.prompt.description'),
                default: 'A new project generated by StackCode.',
            },
            {
                type: 'input',
                name: 'authorName',
                message: t('init.prompt.author_name'),
            },
            {
                type: 'list',
                name: 'stack',
                message: t('init.prompt.stack'),
                choices: [{ name: 'Node.js + TypeScript', value: 'node-ts' }],
            },
            {
                type: 'checkbox',
                name: 'features',
                message: t('init.prompt.features'),
                choices: [
                    { name: 'Docker support', value: 'docker', checked: true },
                    { name: 'Husky for commit linting', value: 'husky', checked: true },
                ],
            },
        ]);

        const projectPath = path.join(process.cwd(), answers.projectName);

        if (fs.existsSync(projectPath)) {
            const { overwrite } = await inquirer.prompt([{
                type: 'confirm',
                name: 'overwrite',
                message: chalk.yellow(t('init.prompt.overwrite').replace('{projectName}', answers.projectName)),
                default: false
            }]);
            if (!overwrite) {
                console.log(chalk.red(t('common.operation_cancelled')));
                return;
            }
        }
        
        console.log(chalk.gray('----------------------------------------------------'));
        console.log(chalk.green(t('init.setup_start')));

        const replacements = {
            projectName: answers.projectName,
            description: answers.description,
            authorName: answers.authorName,
        };

        console.log(chalk.blue(`   ${t('init.step.scaffold')}`));
        scaffoldProject({
            projectPath,
            stack: answers.stack,
            features: answers.features,
            replacements,
        });

        console.log(chalk.blue(`   ${t('init.step.readme')}`));
        fs.writeFileSync(path.join(projectPath, 'README.md'), generateReadmeContent(replacements));
        
        console.log(chalk.blue(`   ${t('init.step.gitignore')}`));
        fs.writeFileSync(path.join(projectPath, '.gitignore'), generateGitignoreContent('node'));
        
        if (answers.features.includes('husky')) {
            console.log(chalk.blue(`   ${t('init.step.husky')}`));
            setupHusky(projectPath);
        }

        console.log(chalk.blue(`   ${t('init.step.git')}`));
        await runCommand('git', ['init'], { cwd: projectPath });
        
        console.log(chalk.blue(`   ${t('init.step.deps')}`));
        await runCommand('npm', ['install'], { cwd: projectPath });

        console.log(chalk.gray('----------------------------------------------------'));
        console.log(chalk.green.bold(t('init.success.ready')));
        console.log(chalk.cyan(`\n${t('init.success.next_steps')}`));
        console.log(`   1. cd ${answers.projectName}`);
        console.log('   2. Open the project in your favorite editor.');
        console.log('   3. Start coding! 🎉');
    },
};