"""
{{projectName}} - {{description}}

A Python application generated by StackCode.
"""

from fastapi import FastAPI
from fastapi.responses import JSONResponse

app = FastAPI(
    title="{{projectName}}",
    description="{{description}}",
    version="1.0.0"
)

@app.get("/")
async def root():
    """Root endpoint returning a welcome message."""
    return JSONResponse({
        "message": "Welcome to {{projectName}}!",
        "status": "running",
        "version": "1.0.0"
    })

@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return JSONResponse({
        "status": "healthy",
        "service": "{{projectName}}"
    })

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
