export const AboutPage = () => {
  return (
    <div className="max-w-3xl mx-auto">
      <h1 className="text-3xl font-bold text-gray-900 mb-6">About {{projectName}}</h1>
      <div className="prose prose-lg text-gray-600">
        <p>
          This is a React application generated by StackCode. It comes with a modern
          development setup including:
        </p>
        <ul>
          <li>React 18 with TypeScript</li>
          <li>Vite for fast development and building</li>
          <li>React Router for navigation</li>
          <li>ESLint for code quality</li>
          <li>Vitest for testing</li>
          <li>Modern CSS with utility classes</li>
        </ul>
        <p>
          Start building your application by editing the components in the 
          <code>src/components</code> directory.
        </p>
      </div>
    </div>
  );
};
